### ISSUE TITLE
Login to Dashboard

### ISSUE THREAD

**Issue by kenfinnigan** [jboss-webide/react-ui#1]
## Login to Dashboard

As a _developer_
I would _be able to access all my workspaces wherever I am_
So that _I can work on any of my projects remotely_

---
### Validation Criteria
- I can enter my credentials directly or specify an OAuth provider
- I'm presented with all the workspaces that I have access to

---
### Tasks
- [ ] Add Login screen
- [ ] Add GitHub OAuth support
- [ ] Add Google OAuth support
- [ ] Add Facebook OAuth support
- [ ] Add Dashboard screen
