### ISSUE TITLE
Import Project from git

### ISSUE THREAD

**Issue by kenfinnigan** [jboss-webide/react-ui#2]
## Import Project from git

As a _developer_
I would _be able to import a project into the workspace from git_
So that _I can edit the existing code_

---
### Validation Criteria
- I can enter or choose which project to be imported from git
- I can provide credentials, if needed
- I'm presented with a workspace containing the project code

---
### Tasks
- [ ] Add screen for selecting a project (For when using GitHub OAuth)
- [ ] Add screen for entering git URL
- [ ] REST API for `git clone`
