### ISSUE TITLE
Import Project from ZIP

### ISSUE THREAD

**Issue by kenfinnigan** [jboss-webide/react-ui#3]
## Import Project from zip

As a _developer_
I would _be able to import a project into the workspace from a zip file_
So that _I can edit the existing code_

---
### Validation Criteria
- I can select a local or remote zip file that contains the project code
- I'm presented with a workspace containing the project code

---
### Tasks
- [ ] Add screen for selecting a local zip file
- [ ] Add screen for entering remote zip file URL
- [ ] REST API for downloading the zip
- [ ] REST API for extracting the zip
- [ ] REST API for `git init`
